Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/lunar64"
  config.vm.provider :virtualbox do |vb|
      vb.name = "vicenteNAT"
  end
  config.vm.network "forwarded_port", guest: 80, host: 8085 # httpd
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.hostname = "vicenteNAT"
  
  config.vm.synced_folder "./dados/", "/home/vagrant/dados" #, type: "virtualbox"
  
  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y net-tools
    apt install -y vim
    apt install -y nmap
    apt install -y docker docker.io docker-compose
    sudo usermod -aG docker vagrant
	cd /home/vagrant/dados/portainer
	docker-compose up -d
	cd /home/vagrant/dados/html
	docker-compose up -d
    apt upgrade -y
    sudo reboot
  SHELL
end
