DROP DATABASE IF EXISTS DBIMPOSTO;
CREATE DATABASE DBIMPOSTO;
USE DBIMPOSTO;

CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL AUTO_INCREMENT
	, NOME VARCHAR(45)
	, ESTADO CHAR(2)
	, VALOR NUMERIC(8,2)
	, ICMS_PERCENTUAL NUMERIC(8,2)
	, ICMS_VALOR NUMERIC(8,2)
	, PRIMARY KEY(IDPRODUTO)
);

CREATE TABLE BASE_ICMS (
	ESTADO CHAR(2) NOT NULL
	, ICMS_PERCENTUAL NUMERIC(8,2)
	, PRIMARY KEY(ESTADO)
);

DELIMITER $$

CREATE TRIGGER TR_PRODUTO_B_I BEFORE INSERT ON PRODUTO FOR EACH ROW 
BEGIN

-- CRIANDO UMA VARIAVEL PARA ARMAZENAR O VALOR DO IMPOSTO
    DECLARE vIMPOSTO NUMERIC(8,2);
	DECLARE vQTDE INT;
    
	SELECT COUNT(ICMS_PERCENTUAL)
	INTO vQTDE
    FROM BASE_ICMS
	WHERE ESTADO = NEW.ESTADO;

	-- CONSULTA PARA BUSCAR O VALOR DO IMPOSTO
	IF (vQTDE = 1) THEN
		SELECT ICMS_PERCENTUAL
		INTO vIMPOSTO
		FROM BASE_ICMS
		WHERE ESTADO = NEW.ESTADO;
        
		SET NEW.ICMS_PERCENTUAL = vIMPOSTO;
		SET NEW.ICMS_VALOR = NEW.VALOR * (vIMPOSTO / 100);
		
	ELSE
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'O estado não tem valor de icms';
	END IF;

END $$

DELIMITER ;

INSERT INTO BASE_ICMS VALUES('AC', 17);
INSERT INTO BASE_ICMS VALUES('AL', 18);
INSERT INTO BASE_ICMS VALUES('AM', 18);
INSERT INTO BASE_ICMS VALUES('AP', 18);
INSERT INTO BASE_ICMS VALUES('BA', 18);
INSERT INTO BASE_ICMS VALUES('CE', 18);
INSERT INTO BASE_ICMS VALUES('DF', 18);
INSERT INTO BASE_ICMS VALUES('ES', 17);
INSERT INTO BASE_ICMS VALUES('GO', 17);
INSERT INTO BASE_ICMS VALUES('MA', 18);
INSERT INTO BASE_ICMS VALUES('MT', 17);
INSERT INTO BASE_ICMS VALUES('MS', 17);
INSERT INTO BASE_ICMS VALUES('MG', 18);
INSERT INTO BASE_ICMS VALUES('PA', 17);
INSERT INTO BASE_ICMS VALUES('PB', 18);
INSERT INTO BASE_ICMS VALUES('PR', 18);
INSERT INTO BASE_ICMS VALUES('PE', 18);
INSERT INTO BASE_ICMS VALUES('PI', 18);
INSERT INTO BASE_ICMS VALUES('RN', 18);
INSERT INTO BASE_ICMS VALUES('RS', 18);
INSERT INTO BASE_ICMS VALUES('RJ', 20);
INSERT INTO BASE_ICMS VALUES('RO', 17.5);
INSERT INTO BASE_ICMS VALUES('RR', 17);
INSERT INTO BASE_ICMS VALUES('SC', 17);
INSERT INTO BASE_ICMS VALUES('SP', 18);
INSERT INTO BASE_ICMS VALUES('SE', 18);
INSERT INTO BASE_ICMS VALUES('TO', 18);

INSERT INTO PRODUTO (NOME, VALOR, ESTADO) VALUES('AGUA', 10, 'SC');
INSERT INTO PRODUTO (NOME, VALOR, ESTADO) VALUES('AGUA', 10, 'SC');

SELECT * FROM PRODUTO;
SELECT * FROM BASE_ICMS;




