SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBCLASSIFICACAO;
CREATE DATABASE DBCLASSIFICACAO;
USE DBCLASSIFICACAO;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(45),
	IDADE INT
);

CREATE TABLE CLASSIFICACAO (	
	CRIANCAS INT,
	JOVENS INT,
	ADULTOS INT
);

INSERT INTO CLASSIFICACAO VALUES (0, 0, 0);

DELIMITER $$

CREATE TRIGGER TR_ALUNO_AI AFTER INSERT ON ALUNO FOR EACH ROW
BEGIN 
	IF NEW.IDADE < 10 THEN
		UPDATE CLASSIFICACAO SET CRIANCAS = CRIANCAS + 1;
    ELSEIF NEW.IDADE >= 10 AND NEW.IDADE < 18 THEN
		UPDATE CLASSIFICACAO SET JOVENS = JOVENS + 1;
	ELSEIF NEW.IDADE > 18 THEN
		UPDATE CLASSIFICACAO SET ADULTOS = ADULTOS + 1;
	END IF;
END $$

CREATE TRIGGER TR_ALUNO_AD AFTER DELETE ON ALUNO FOR EACH ROW
BEGIN 
	IF OLD.IDADE < 10 THEN
		UPDATE CLASSIFICACAO SET CRIANCAS = CRIANCAS - 1;
    ELSEIF OLD.IDADE >= 10 AND OLD.IDADE < 18 THEN
		UPDATE CLASSIFICACAO SET JOVENS = JOVENS - 1;
	ELSE
		UPDATE CLASSIFICACAO SET ADULTOS = ADULTOS - 1;
	END IF;
END $$

CREATE TRIGGER TR_ALUNO_AU AFTER UPDATE ON ALUNO FOR EACH ROW
BEGIN 
	IF OLD.IDADE < 10 THEN
		UPDATE CLASSIFICACAO SET CRIANCAS = CRIANCAS - 1;
    ELSEIF OLD.IDADE > 10 AND NEW.IDADE < 18 THEN
		UPDATE CLASSIFICACAO SET JOVENS = JOVENS - 1;
	ELSEIF OLD.IDADE > 18 THEN
		UPDATE CLASSIFICACAO SET ADULTOS = ADULTOS - 1;
	END IF;
    
    -- CAMPO NOVO
    
	IF NEW.IDADE < 10 THEN
		UPDATE CLASSIFICACAO SET CRIANCAS = CRIANCAS + 1;
    ELSEIF NEW.IDADE >= 10 AND NEW.IDADE < 18 THEN
		UPDATE CLASSIFICACAO SET JOVENS = JOVENS + 1;
	ELSEIF NEW.IDADE > 18 THEN
		UPDATE CLASSIFICACAO SET ADULTOS = ADULTOS + 1;
	END IF;
END $$

DELIMITER $$
CREATE TRIGGER TR_ALUNO_BI BEFORE INSERT ON ALUNO FOR EACH ROW
BEGIN
    -- Check if age is valid
    IF NEW.IDADE < 0 OR NEW.IDADE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Campo idade é inválido!';
    END IF;
END $$

DELIMITER ;

INSERT INTO ALUNO (NOME, IDADE) VALUES ('PEDRO', '18');
INSERT INTO ALUNO (NOME, IDADE) VALUES ('LIRIS', 19);
INSERT INTO ALUNO (NOME, IDADE) VALUES ('CARUSO', 15);
INSERT INTO ALUNO (NOME, IDADE) VALUES ('BRUNO', 5);

DELETE FROM ALUNO WHERE NOME = 'LIRIS';

UPDATE ALUNO SET IDADE = 19 WHERE NOME = 'PEDRO';

SELECT * FROM ALUNO;
SELECT * FROM CLASSIFICACAO;