SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBESTATISTICA;
CREATE DATABASE DBESTATISTICA;
USE DBESTATISTICA;

CREATE TABLE PESSOA (
	IDPESSOA INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(45)
	, SEXO CHAR(1)
);

CREATE TABLE ESTATISTICA (	
	HOMEM INT
	, MULHER INT
);

-- CRIANDO A LINHA NA TABELA ESTATISTICA PARA ATUALIZAÇÃO DE QTDE DE PESSOA
INSERT INTO ESTATISTICA VALUES (0, 0);


DELIMITER $$

CREATE TRIGGER TR_PESSOA_AI AFTER INSERT ON PESSOA FOR EACH ROW
BEGIN

-- VERIFICADNO SE O VALOR INFORMADO PARA O CAMPO SEXO É FEMININO
	IF NEW.SEXO = 'F' THEN
    -- ATUALIZANDO A TABELA ESTATISTICA
		UPDATE ESTATISTICA SET MULHER = MULHER + 1;
    ELSEIF NEW.SEXO = 'M' THEN
    UPDATE ESTATISTICA SET HOMEM = HOMEM + 1;
    END IF;
    
	
    
END $$

DELIMITER ;


SELECT * FROM PESSOA;
SELECT * FROM ESTATISTICA;

INSERT INTO PESSOA(NOME, SEXO) VALUES ('ANA', 'F');