Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.provider :virtualbox do |vb|
      vb.name = "vicentedebian"
  end
  config.vm.network "forwarded_port", guest: 80, host: 8085 # httpd
  config.vm.network "forwarded_port", guest: 9090, host: 9090 # nginx
  config.vm.network "forwarded_port", guest: 8080, host: 8080 # apache 
  config.vm.hostname = "vicentedebian"
  config.vm.network "public_network"
  config.vm.synced_folder "./dados/", "/home/vagrant/dados" #, type: "virtualbox"
  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y net-tools
    apt install -y vim
    apt install -y nmap curl
    apt install -y docker docker.io docker-compose
    sudo usermod -aG docker vagrant
    apt upgrade -y
    sudo reboot
  SHELL
end